name: Build-To-Deploy
 
on:
  workflow_dispatch:
 
jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: dev
  
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
       fetch-depth: 0 # required for github-action-get-previous-tag

    - name: Create release
      id: create_release_id
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.next.outputs.version }}
        release_name: Release ${{ steps.next.outputs.version }}

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
 
    - name: Build the docker image and push it to ACR
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/mydocker:${{ github.sha }}
        file: ./Dockerfile
        
  
