name: Build-and-Version
 
on:
  #workflow_dispatch:
   push:
     branches: [main]
 
jobs:
  docker_build_push_acr:
    name: 'Increment Build'
    runs-on: ubuntu-latest
    environment: dev
  
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for github-action-get-previous-tag

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}



      #- name: Get Latest Tag
      #  id: latest-tag
      #  run: |
      #    latest_tag=$(git describe --tags 'git rev-list --tags --max-count=1')   


      - name: GitHub Tag Name example 
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          #echo "Latest Tag ${{ steps.latest-tag.outputs.latest_tag }}"

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
        with:
          title: MyReleaseMessage
          tag: MyTag


      
