name: Build-and-Version
 
on:
  #workflow_dispatch:
   push:
     branches: [main]
 
jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: dev
  
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
  
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Print variables
      run: ls -ltr /home/runner/work/mydocker
        
    - name: Get variables
      id: get_version
      run: |
        echo 'version=$(cat ./VERSION)' >> $GITHUB_OUTPUT
        #echo "VERSION=$VER" >> $GITHUB_ENV

    - name: Debug
      run: echo 'get_version:' ${{ steps.get_version.outputs.VERSION }}

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.ACCESS_TOKEN_GITHUB}}
             
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: v${{ steps.get_version.outputs.version }}.${{ steps.buildnumber.outputs.build_number }}
        prerelease: false

          
        
  
