name: Build-and-Version
 
on:
  #workflow_dispatch:
   push:
     branches: [main]
 
jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: dev
  
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
  
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # required for github-action-get-previous-tag
      
    - name: Print variables
      run: ls -ltr /home/runner/work/mydocker
        
    - name: Get variables
      id: get_version
      run: |
        echo 'version=$(cat ./VERSION)'++ >> $GITHUB_OUTPUT

    - name: Debug
      run: echo 'get_version:' ${{ steps.get_version.outputs.version }}



          
        
  
